### ISSUE TITLE
run issue

### ISSUE THREAD

**Issue by Tsunami014** [vicuna-tools/vicuna-installation-guide#13]
I made the thing in a build folder which worked but then in the instructions it says run some code that specifies a `./main` folder or location or something which does not exist - did I do something wrong and where is the folder/file/whatever that isn't there and how do I get it?

**Comment by fredi-python** [comment]
Could you give more details of the steps you took?

**Comment by Tsunami014** [comment]
Oh sorry, nvm

What I did was I built it in a build folder and it couldn't find the directory `./main` that was referenced in the last piece of code,
I needed to just run the entire code as it was, and it worked
I'm fine now!
