### ISSUE TITLE
Hugging face wget command fails with Username/Password Authentication Failed.

### ISSUE THREAD

**Issue by AverageGuy** [vicuna-tools/vicuna-installation-guide#3]
`wget https://huggingface.co/TheBloke/vicuna-13B-1.1-GPTQ-4bit-128g-GGML/resolve/main/vicuna-13B-1.1-GPTQ-4bit-128g.GGML.bin
--2023-05-06 13:37:02--  https://huggingface.co/TheBloke/vicuna-13B-1.1-GPTQ-4bit-128g-GGML/resolve/main/vicuna-13B-1.1-GPTQ-4bit-128g.GGML.bin
Resolving huggingface.co (huggingface.co)... 13.32.230.100, 13.32.230.67, 13.32.230.49, ...
Connecting to huggingface.co (huggingface.co)|13.32.230.100|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.
`

**Comment by Snookmz** [comment]
I'll just add to this that the command comes from the installation guide found here:
https://github.com/vicuna-tools/vicuna-installation-guide

**Comment by constantOut** [comment]
I've found another repo with these files, but there is an error loading them...
https://huggingface.co/4bit/vicuna-13B-1.1-GPTQ-4bit-128g-GGML/tree/main

**Comment by fredi-python** [comment]
TheBloke removed the ggmls cause of bad quality. 
![IMG_20230508_152105.jpg](https://user-images.githubusercontent.com/83492589/236835133-71964c79-5895-4384-aa4a-b298a15d9803.jpg)

I will update the repo soon

**Comment by fredi-python** [comment]
Updated!
